services:

  web:
    image: nginx
    container_name: web
    ports:
      - "8080:80"
    networks:
      - frontend_net

  api:
    image: python:3.9
    container_name: api
    command: sh -c "pip install flask && python app.py"
    volumes:
      - ./api:/app
    working_dir: /app
    networks:
      - frontend_net
      - backend_net

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend_net

  attacker:
    image: alpine
    container_name: attacker
    command: sh -c "apk add --no-cache nmap curl bash && sleep 3600"
    networks:
      - frontend_net

networks:

  frontend_net:
    driver: bridge

  backend_net:
    driver: bridge
    internal: true